### ISSUE TITLE
Add timeouts

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/bisectbot#12]
Given that these bots were initially made for developers, there are no timeouts whatsoever. If something takes 200 seconds to run then nothing will kill it.

Sometimes that's fine, but given that we now use these bots for various random stuff, it's time to implement a time limit. Would be great if it was configurable per bot. This way, for example, we can have 200s timeout for bisectable, 20s timeout for evalable, 50s for committable and so on.

**Comment by MasterDuke17** [comment]
Implemented in 1182968. The default is 10 seconds, a bot can override that by implementing timeout(), which just returns the number of seconds to wait.
