### ISSUE TITLE
bisectable: show actual starting points somewhere in the output

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/bisectbot#15]
Otherwise people don't really see what is being bisected.

Is there any way to do that without printing a fourth line?

**Comment by MasterDuke17** [comment]
Could put them in the first line of output. E.g., 

- "On both starting points **(good=$good, bad=$bad)** the exit code is $exit_bad and the output is identical as well"
- "Exit code is $exit_bad on both starting points **(good=$good, bad=$bad)**, bisecting by using the output"
- "**For the given starting points (good=$good, bad=$bad),** exit code on a 'good' revision is $exit_good (which is bad), bisecting with inverted logic"

Or we could add a line to the bisect log.

**Comment by AlexDaniel** [comment]
I like it! But drop the comma, so that it will be possible to use the same string in your query (or allow commas in the query).

Should we also resolve ``HEAD`` and display the commit hash instead? bisectable is currently set to build new versions every three hours, so this information is probably useful. Otherwise it will say ``(good=2015.12 bad=HEAD)``. You can already see the commit hash in the bisect log, but I'm not sure if that is awesome enough.

**Comment by MasterDuke17** [comment]
Implemented in 83b6e73.
